import type { VtexComponentDefinition } from '../types'

export const flexLayoutRow: VtexComponentDefinition = {
    type: 'flex-layout.row',
    label: 'Flex Layout Row',
    icon: 'Rows3',
    category: 'layout',
    acceptsChildren: true,
    propsSchema: [
        { name: 'blockClass', type: 'string', label: 'Block Class', default: '' },
        { name: 'borderColor', type: 'string', label: 'Border Color', default: '' },
        { name: 'borderWidth', type: 'number', label: 'Border Width (0-5)', default: 0 },
        { name: 'border', type: 'string', label: 'Border (top, right, bottom, left, all)', default: '' },
        { name: 'colGap', type: 'number', label: 'Column Gap (0-10)', default: 0 },
        {
            name: 'colSizing',
            type: 'enum',
            label: 'Column Sizing',
            default: 'equal',
            options: [
                { value: 'equal', label: 'Equal' },
                { value: 'auto', label: 'Auto' },
            ],
        },
        { name: 'fullWidth', type: 'boolean', label: 'Full Width', default: false },
        {
            name: 'horizontalAlign',
            type: 'enum',
            label: 'Horizontal Align',
            default: 'left',
            options: [
                { value: 'left', label: 'Left' },
                { value: 'center', label: 'Center' },
                { value: 'right', label: 'Right' },
                { value: 'between', label: 'Between' },
                { value: 'around', label: 'Around' },
            ],
        },
        {
            name: 'colJustify',
            type: 'enum',
            label: 'Column Justify',
            default: 'between',
            options: [
                { value: 'between', label: 'Between' },
                { value: 'around', label: 'Around' },
            ],
        },
        { name: 'marginBottom', type: 'number', label: 'Margin Bottom (0-10)', default: 0 },
        { name: 'marginTop', type: 'number', label: 'Margin Top (0-10)', default: 0 },
        { name: 'paddingBottom', type: 'number', label: 'Padding Bottom (0-10)', default: 0 },
        { name: 'paddingTop', type: 'number', label: 'Padding Top (0-10)', default: 0 },
        { name: 'preserveLayoutOnMobile', type: 'boolean', label: 'Preserve Layout On Mobile', default: false },
        { name: 'preventHorizontalStretch', type: 'boolean', label: 'Prevent Horizontal Stretch', default: false },
        { name: 'preventVerticalStretch', type: 'boolean', label: 'Prevent Vertical Stretch', default: false },
        { name: 'rowGap', type: 'number', label: 'Row Gap (0-10)', default: 0 },
        { name: 'htmlId', type: 'string', label: 'HTML ID', default: '' },
        { name: 'arialabel', type: 'string', label: 'Aria Label', default: '' },
    ],
}
